hostname: uk-power.ijmacd.com
web:
  replicaCount: 1
  repository:
    image: docker.io/ijmacd/uk-power
  tls:
    enabled: false
  local:
    enabled: false
  resources:
    requests:
      cpu: 5m
      memory: 31Mi
    limits:
      memory: 31Mi
