{{ if .Values.web.local.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-index-dev"
data:
  {{- $files := .Files }}
  {{- range tuple "data/index.html" }}
  {{ base . }}: |
{{ $files.Get . | indent 4 }}
  {{- end }}
{{- end }}